language: java

sudo: false

jdk:
  - oraclejdk8

deploy:
  provider: openshift
  user: $OPENSHIFT_USER
  password: $OPENSHIFT_PASSWORD
  domain: jdroid
  app:
      master: staging

script: ./gradlew check uploadArchives -PLOCAL_UPLOAD=false --stacktrace