defaults: &defaults
  working_directory: ~/jdroid-java-webapp
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    JVM_OPTS: -Xmx3200m
    LOCAL_MAVEN_REPO: ~/repo
    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: app-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Assembling
          command: ./gradlew assemble --refresh-dependencies --stacktrace --scan

      - save_cache:
          paths:
            - ~/.gradle
          key: app-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Saving jars
          command: |
            mkdir -p ~/jars/
            find . -type f -regex ".*/build/libs/.*jar" -exec cp {} ~/jars/ \;
          when: always

      - store_artifacts:
          path: ~/jars
          destination: jars

  verify:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: app-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Verifying
          command: ./gradlew check --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
          key: app-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Saving test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ./jdroid-java-webapp-core/build/reports/tests/test
          destination: jdroid-java-webapp-core/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-facebook/build/reports/tests/test
          destination: jdroid-java-webapp-facebook/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-firebase-firestore/build/reports/tests/test
          destination: jdroid-java-webapp-firebase-firestore/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-firebase-admin/build/reports/tests/test
          destination: jdroid-java-webapp-firebase-admin/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-firebase-fcm/build/reports/tests/test
          destination: jdroid-java-webapp-firebase-fcm/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-push/build/reports/tests/test
          destination: jdroid-java-webapp-push/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-sample/build/reports/tests/test
          destination: jdroid-java-webapp-sample/tests

      - store_artifacts:
          path: ./jdroid-java-webapp-twitter/build/reports/tests/test
          destination: jdroid-java-webapp-twitter/tests

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: app-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew publish -PLOCAL_UPLOAD=false --stacktrace

workflows:
  version: 2
  commit:
    jobs:
      - build
      - verify:
          requires:
            - build
      - deploy:
          requires:
            - verify